<a href="https://colab.research.google.com/github/Ayazmj/northstar-database-analytics-coursework/blob/main/notebooks/00_project_setup_and_data_audit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00 Project Setup and Data Audit

## Project Title
Integrated Database and Analytics Solution for NorthStar Urban Mobility and Logistics

## Purpose
This notebook performs the initial dataset audit for the NorthStar case study. It checks file availability, dataset structure, missing values, duplicate records, data types, and initial data quality issues before SQL, R, Python analytics, and MongoDB development are carried out.

## Technologies Used
- Google Colab
- Python
- Pandas
- NumPy
- GitHub

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
import pandas as pd
import numpy as np
import os

data_path = "/content/drive/MyDrive/NorthStar_Database_Analytics/data "

files = {
    "customers": "customers.csv",
    "orders": "orders.csv",
    "deliveries": "deliveries.csv",
    "drivers": "drivers.csv",
    "vehicles": "vehicles.csv",
    "hubs": "hubs.csv",
    "complaints": "complaints.csv",
    "incidents": "incidents.csv",
    "app_events": "app_events.csv",
    "data_dictionary": "data_dictionary.csv"
}

datasets = {}

for name, filename in files.items():
    file_path = os.path.join(data_path, filename)

    if os.path.exists(file_path):
        datasets[name] = pd.read_csv(file_path)
        print(f"{name} loaded successfully: {datasets[name].shape}")
    else:
        print(f"{name} NOT FOUND: {file_path}")

customers loaded successfully: (650, 9)
orders loaded successfully: (1250, 11)
deliveries loaded successfully: (950, 13)
drivers loaded successfully: (170, 8)
vehicles loaded successfully: (120, 8)
hubs loaded successfully: (8, 5)
complaints loaded successfully: (320, 10)
incidents loaded successfully: (280, 7)
app_events loaded successfully: (640, 10)
data_dictionary loaded successfully: (9, 3)

In [15]:
audit_summary = []

for name, df in datasets.items():
    audit_summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "missing_values_total": df.isnull().sum().sum()
    })

audit_df = pd.DataFrame(audit_summary)
audit_df

           dataset  rows  columns  duplicate_rows  missing_values_total
0        customers   650        9               0                    33
1           orders  1250       11               0                    25
2       deliveries   950       13               0                    33
3          drivers   170        8               0                     7
4         vehicles   120        8               0                     4
5             hubs     8        5               0                     0
6       complaints   320       10               0                    16
7        incidents   280        7               0                    17
8       app_events   640       10               0                   144
9  data_dictionary     9        3               0                     0

## Initial Dataset Audit Summary

The initial data audit confirms that all required NorthStar dataset files were successfully loaded into Google Colab. The audit summary records the number of rows, columns, duplicate rows, and missing values in each dataset. This step is important because it helps identify data quality issues before performing SQL analysis, R analytics, Python processing, and MongoDB database development.

In [16]:
for name, df in datasets.items():
    print("\n" + "="*60)
    print(f"DATASET: {name.upper()}")
    print("="*60)
    print(df.info())

============================================================
DATASET: CUSTOMERS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB
None

============================================================
DATASET: ORDERS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB
None

============================================================
DATASET: DELIVERIES
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB
None

============================================================
DATASET: DRIVERS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB
None

============================================================
DATASET: VEHICLES
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB
None

============================================================
DATASET: HUBS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes
None

============================================================
DATASET: COMPLAINTS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    object
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 25.1+ KB
None

============================================================
DATASET: INCIDENTS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    object
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: float64(1), object(6)
memory usage: 15.4+ KB
None

============================================================
DATASET: APP_EVENTS
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    object
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: int64(2), object(8)
memory usage: 50.1+ KB
None

============================================================
DATASET: DATA_DICTIONARY
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   file_name     9 non-null      object
 1   record_count  9 non-null      int64
 2   description   9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes
None

In [17]:
for name, df in datasets.items():
    print("\n" + "="*60)
    print(f"MISSING VALUES IN {name.upper()}")
    print("="*60)

    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    if missing.empty:
        print("No missing values found.")
    else:
        print(missing)

============================================================
MISSING VALUES IN CUSTOMERS
============================================================
loyalty_score        20
preferred_channel    13
dtype: int64

============================================================
MISSING VALUES IN ORDERS
============================================================
booking_channel    25
dtype: int64

============================================================
MISSING VALUES IN DELIVERIES
============================================================
delivery_completed_at            19
customer_rating_post_delivery    14
dtype: int64

============================================================
MISSING VALUES IN DRIVERS
============================================================
training_score    7
dtype: int64

============================================================
MISSING VALUES IN VEHICLES
============================================================
battery_health_pct    4
dtype: int64

============================================================
MISSING VALUES IN HUBS
============================================================
No missing values found.

============================================================
MISSING VALUES IN COMPLAINTS
============================================================
compensation_amount    16
dtype: int64

============================================================
MISSING VALUES IN INCIDENTS
============================================================
resolved_hours    17
dtype: int64

============================================================
MISSING VALUES IN APP_EVENTS
============================================================
order_id    144
dtype: int64

============================================================
MISSING VALUES IN DATA_DICTIONARY
============================================================
No missing values found.

In [18]:
for name, df in datasets.items():
    print("\n" + "="*60)
    print(f"PREVIEW: {name.upper()}")
    print("="*60)
    display(df.head())

============================================================
PREVIEW: CUSTOMERS
============================================================

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

============================================================
PREVIEW: ORDERS
============================================================

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

============================================================
PREVIEW: DELIVERIES
============================================================

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

============================================================
PREVIEW: DRIVERS
============================================================

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

============================================================
PREVIEW: VEHICLES
============================================================

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

============================================================
PREVIEW: HUBS
============================================================

  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88

============================================================
PREVIEW: COMPLAINTS
============================================================

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18

============================================================
PREVIEW: INCIDENTS
============================================================

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

============================================================
PREVIEW: APP_EVENTS
============================================================

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

============================================================
PREVIEW: DATA_DICTIONARY
============================================================

,file_name,record_count,description
0,hubs.csv,8,Operational hubs and control points
1,customers.csv,650,Customer master data with engagement and loyal...
2,drivers.csv,170,Driver workforce data with training and rating...
3,vehicles.csv,120,Fleet asset data including battery and mainten...
4,orders.csv,1250,Service orders across mobility and logistics o...

In [19]:
audit_df

           dataset  rows  columns  duplicate_rows  missing_values_total
0        customers   650        9               0                    33
1           orders  1250       11               0                    25
2       deliveries   950       13               0                    33
3          drivers   170        8               0                     7
4         vehicles   120        8               0                     4
5             hubs     8        5               0                     0
6       complaints   320       10               0                    16
7        incidents   280        7               0                    17
8       app_events   640       10               0                   144
9  data_dictionary     9        3               0                     0

## Initial Dataset Audit Findings

The initial dataset audit shows that all required NorthStar datasets were successfully loaded into Google Colab. No duplicate rows were found across the datasets, which suggests that record-level duplication is not a major issue at this stage.

However, missing values are present in several important operational datasets. The highest number of missing values appears in the app_events dataset, followed by customers, deliveries, orders, incidents, complaints, drivers, and vehicles. This supports the case study problem that NorthStar's data environment is fragmented and inconsistent, especially where mobile platform events and operational records need to be combined.

The hubs and data_dictionary datasets contain no missing values, meaning they can be used as reliable reference datasets during analysis. Further cleaning will be required before performing SQL queries, R analytics, Python feature engineering, and MongoDB document modelling.

In [20]:
missing_details = []

for name, df in datasets.items():
    for column in df.columns:
        missing_count = df[column].isnull().sum()
        if missing_count > 0:
            missing_details.append({
                "dataset": name,
                "column": column,
                "missing_count": missing_count,
                "missing_percentage": round((missing_count / len(df)) * 100, 2)
            })

missing_details_df = pd.DataFrame(missing_details)
missing_details_df.sort_values(by="missing_count", ascending=False)

,dataset,column,missing_count,missing_percentage
9,app_events,order_id,144,22.50
2,orders,booking_channel,25,2.00
0,customers,loyalty_score,20,3.08
3,deliveries,delivery_completed_at,19,2.00
8,incidents,resolved_hours,17,6.07
7,complaints,compensation_amount,16,5.00
4,deliveries,customer_rating_post_delivery,14,1.47
1,customers,preferred_channel,13,2.00
5,drivers,training_score,7,4.12
6,vehicles,battery_health_pct,4,3.33

In [21]:
output_path = "/content/drive/MyDrive/NorthStar_Database_Analytics/outputs/"

os.makedirs(output_path, exist_ok=True)

audit_df.to_csv(output_path + "initial_dataset_audit_summary.csv", index=False)
missing_details_df.to_csv(output_path + "missing_values_by_column.csv", index=False)

print("Audit outputs saved successfully.")

Audit outputs saved successfully.